version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27037:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
  open-api-doc:
    build: open-api-doc
    ports:
      - '4000:4000'
    volumes:
      - /app/node_modules
      - ./open-api-doc:/app
  frontend:
    build: frontend
    environment:
      - REACT_APP_GOOGLE_RECAPTCHA_KEY=${REACT_APP_GOOGLE_RECAPTCHA_KEY}
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - '5000:5000'
    environment:
      - CLOUDINARY_HOST=${CLOUDINARY_HOST}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - PORT=${PORT}
      - DB_CONNECT=${DB_CONNECT}
      - DB_TEST_CONNECT=${DB_TEST_CONNECT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - USER_EMAIL=${USER_EMAIL}
      - PASS=${PASS}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - /app/node_modules
      - ./backend:/app
